{% set name = "interpret-core" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/interpretml/interpret/archive/0895eb56e37b7a2045e34bc5cdb3679419002da4.tar.gz
  # curl -sL https://github.com/interpretml/interpret/archive/0895eb56e37b7a2045e34bc5cdb3679419002da4.tar.gz | openssl sha256
  sha256: d8762a8b2a09dce9f9876ec9bd70ff1ab33ead449c2054e2c21a66807a79d56b
  # url: https://github.com/interpretml/interpret/archive/v{{ version }}.tar.gz

build:
  number: 0
  noarch: python
  script: cd ./python/interpret-core/ && {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    # specifying nodejs ==* prevents us from building it 3 times for different versions of nodejs (after running @conda-forge-admin please rerender)
    - nodejs ==16.*
  host:
    - python >=3.7.*
    - pip
    - setuptools
    - wheel
  run:
    - python >=3.7.*
    - libebm =={{ version }}

test:
  requires:
    # for pip check
    - pip
    # in setup.py
    - setuptools
    - wheel
    # Equiv. to required.
    - numpy >=1.11.1
    - scipy >=0.18.1
    - pandas >=0.19.2
    - scikit-learn >=0.18.1
    - joblib >=0.11
    # Equiv. to extras.
    - psutil >=5.6.2
    - ipykernel >=4.10.0
    - ipython >=5.5.0
    - plotly >=3.8.1
    - lime >=0.1.1.33
    - SALib >=1.3.3
    - shap >=0.28.5
    - dill >=0.2.5
    - treeinterpreter >=0.2.2
    - dash >=1.0.0 # dash 2.* removed the dependencies on: dash-html-components, dash-core-components, dash-table
    - dash-html-components # this seems to be needed by pip check, but probably not by the package if dash >=2.*
    - dash-core-components # this seems to be needed by pip check, but probably not by the package if dash >=2.*
    - dash-table # this seems to be needed by pip check, but probably not by the package if dash >=2.*
    - dash_cytoscape >=0.1.1
    - gevent >=1.3.6
    - requests >=2.19.0
    # pure test requirements
    - pytest >=4.3.0
    - pytest-runner >=4.4
    - pytest-xdist >=1.29
    - nbconvert >=5.4.1
    - selenium >=3.141.0
    - pytest-cov >=2.6.1
    # ----remove linter temporarily   - flake8 >=3.7.7
    - jupyter >=1.0.0
    - ipywidgets >=7.4.2
  imports:
    - interpret
  commands:
    - pip check
    # - pip list
    # - python -m pytest --pyargs interpret -vv -n auto --doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html

about:
  home: https://github.com/interpretml/interpret
  summary: Fit interpretable machine learning models. Explain blackbox machine learning.
  description: |
    Core system for **the** interpret package.

    https://github.com/interpretml/interpret
  license: MIT
  license_file: LICENSE
  doc_url: https://interpret.ml/docs/getting-started
  dev_url: https://interpret.ml/docs/installation-guide.html

extra:
  recipe-maintainers:
    - paulbkoch
    - interpret-ml
