{% set name = "interpret-core" %}
{% set version = "0.2.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  # curl -sL https://github.com/username/reponame/archive/.tar.gz | openssl sha256
  sha256: f9b3123754fa7f0f91aad5f6c0afaa9b3841e466b24fa441da80b292c398ee91
  url: https://github.com/interpretml/interpret/archive/19b0188c841a67a8fa7bf42347d00d81bcca472b.tar.gz
  # url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  # url: https://github.com/interpretml/interpret/releases/download/{{ version }}/interpret-core-{{ version }}.tar.gz
  # url: https://github.com/interpretml/interpret/archive/v{{ version }}.tar.gz
  # git_url: https://github.com/interpretml/interpret.git
  # git_rev: "v{{ version }}"
  # git_depth: 1

build:
  number: 0
  #skip: True  # [py>=39 or py2k or py<37]
  script: sh ./build.sh && cd ./python/interpret-core/js/ && npm install && npm run build-prod && cd .. && {{ PYTHON }} -m pip install . -vv  # [not win]
  script: .\build.bat && cd .\python\interpret-core\js\ && npm install && npm run build-prod && cd .. && {{ PYTHON }} -m pip install . -vv  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python >=3.7.*
    - setuptools
    - wheel
    # specifying nodejs ==* prevents us from building it 3 times for different versions of nodejs (after running @conda-forge-admin please rerender)
    - nodejs ==*
  run:
    - python >=3.7.*
  run_constrained:
    # in setup.py
    - setuptools
    - wheel
    # Equiv. to required.
    - numpy >=1.11.1
    - scipy >=0.18.1
    - pandas >=0.19.2
    - scikit-learn >=0.18.1
    - joblib >=0.11
    # Equiv. to extras.
    - psutil >=5.6.2
    - ipykernel >=5.1.0
    - ipython >=7.4.0
    - plotly >=3.8.1
    - lime >=0.1.1.33
    - SALib >=1.3.3
    - shap >=0.28.5
    - dill >=0.2.5
    - skope-rules >=1.0.1
    - treeinterpreter >=0.2.2
    - dash >=1.0.0
    - dash_cytoscape >=0.1.1
    - gevent >=1.3.6
    - requests >=2.19.0

test:
  requires:
    # in setup.py
    - setuptools
    - wheel
    # Equiv. to required.
    - numpy >=1.11.1
    - scipy >=0.18.1
    - pandas >=0.19.2
    - scikit-learn >=0.18.1
    - joblib >=0.11
    # Equiv. to extras.
    - psutil >=5.6.2
    - ipykernel >=5.1.0
    - ipython >=7.4.0
    - plotly >=3.8.1
    - lime >=0.1.1.33
    - SALib >=1.3.3
    - shap >=0.28.5
    - dill >=0.2.5
    - skope-rules >=1.0.1
    - treeinterpreter >=0.2.2
    - dash >=1.0.0
    - dash_cytoscape >=0.1.1
    - gevent >=1.3.6
    - requests >=2.19.0
    # pure test requirements
    - pytest >=4.3.0, <=6.0.2
    - pytest-runner >=4.4
    - pytest-xdist >=1.29
    - nbconvert >=5.4.1
    - selenium >=3.141.0
    - pytest-cov >=2.6.1
    - flake8 >=3.7.7
    - jupyter >=1.0.0
    - ipywidgets >=7.4.2
  imports:
    - interpret

about:
  home: https://github.com/interpretml/interpret
  summary: Fit interpretable machine learning models. Explain blackbox machine learning.
  description: |
    Core system for **the** interpret package.

    https://github.com/interpretml/interpret
  license: MIT
  license_file: LICENSE
  doc_url: https://interpret.ml/docs/getting-started
  dev_url: https://interpret.ml/docs/installation-guide.html

extra:
  recipe-maintainers:
    - paulbkoch
    - interpret-ml
