{% set name = "interpret-core" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/interpretml/interpret/archive/0b22c1d6de32fefd6cdfaadbe7762ffd536c1d10.tar.gz
  # curl -sL https://github.com/interpretml/interpret/archive/0b22c1d6de32fefd6cdfaadbe7762ffd536c1d10.tar.gz | openssl sha256
  sha256: 32093001b384f6fcca88231abe79b359df4110f76164056e1d7428585cba0779

build:
  number: 0
  noarch: python
  script: cd ./python/interpret-core/ && {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    # specifying nodejs ==x.* prevents us from building it 3 times for different versions of nodejs
    - nodejs ==16.*
  host:
    - python >=3.7.*
    - pip
    - setuptools
  run:
    - python >=3.7.*
    - libebm =={{ version }}

test:
  requires:
    # for pip check
    - pip
    # in setup.py
    - setuptools
    # Equiv. to required.
    - numpy >=1.11.1
    - scipy >=0.18.1
    - pandas >=0.19.2
    - scikit-learn >=0.18.1
    - joblib >=0.11
    # Equiv. to extras.
    - psutil >=5.6.2
    - ipykernel >=4.10.0
    - ipython >=5.5.0
    - plotly >=3.8.1
    - lime >=0.1.1.33
    - SALib >=1.3.3
    - shap >=0.28.5
    - dill >=0.2.5
    - skope-rules >=1.0.1
    - treeinterpreter >=0.2.2
    - dash >=1.0.0 # dash 2.* removed the dependencies on: dash-html-components, dash-core-components, dash-table
    - dash-core-components >=1.0.0 # dash 2.* removes the need for this dependency
    - dash-html-components >=1.0.0 # dash 2.* removes the need for this dependency
    - dash-table >=4.1.0 # dash 2.* removes the need for this dependency
    - dash_cytoscape >=0.1.1
    - gevent >=1.3.6
    - requests >=2.19.0
    # pure test requirements
    - pytest >=4.3.0
    - pytest-runner >=4.4
    - pytest-xdist >=1.29
    - nbconvert >=5.4.1
    - selenium >=3.141.0
    - pytest-cov >=2.6.1
    # ----remove linter temporarily   - flake8 >=3.7.7
    - jupyter >=1.0.0
    - ipywidgets >=7.4.2
  imports:
    - interpret
  commands:
    - pip check
    # - pip list
    - python -m pytest --pyargs interpret -vv -n auto --doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html

about:
  home: https://github.com/interpretml/interpret
  summary: Fit interpretable models. Explain blackbox machine learning.
  description: |
    Core system for the interpret package.

    https://github.com/interpretml/interpret
  license: MIT
  license_file: LICENSE
  doc_url: https://interpret.ml/docs/getting-started
  dev_url: https://interpret.ml/docs/installation-guide.html

extra:
  recipe-maintainers:
    - paulbkoch
    - interpret-ml
