{% set name = "interpret-core" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/interpretml/interpret/archive/7e5f94d3a3d946bdffe1b4124036f43dd45b44dc.tar.gz
  # curl -sL https://github.com/interpretml/interpret/archive/7e5f94d3a3d946bdffe1b4124036f43dd45b44dc.tar.gz | openssl sha256
  sha256: d52a4b7868697fcdd021242d7fedf662d3a1533a50168750510ef63eadd1f945
  # url: https://github.com/interpretml/interpret/archive/v{{ version }}.tar.gz

build:
  number: 2
  script: cd ./python/interpret-core/ && {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    # specifying nodejs ==* prevents us from building it 3 times for different versions of nodejs (after running @conda-forge-admin please rerender)
    - nodejs ==16.*
  host:
    - python  {{ python }}
    - pip
    - setuptools
    - wheel
  run:
    - python  {{ python }}

test:
  requires:
    # for pip check
    - pip
    # in setup.py
    - setuptools
    - wheel
    # Equiv. to required.
    - numpy >=1.11.1
    - scipy >=0.18.1
    - pandas >=0.19.2
    - scikit-learn >=0.18.1
    - joblib >=0.11
    # Equiv. to extras.
    - psutil >=5.6.2
    - ipykernel >=5.1.0
    - ipython >=7.4.0
    - plotly >=3.8.1
    - lime >=0.1.1.33
    - SALib >=1.3.3
    - shap >=0.28.5
    - dill >=0.2.5
    - treeinterpreter >=0.2.2
    - dash >=1.0.0 # dash 2.* removed the dependencies on: dash-html-components, dash-core-components, dash-table
    - dash-html-components # this seems to be needed by pip check, but probably not by the package if dash >=2.*
    - dash-core-components # this seems to be needed by pip check, but probably not by the package if dash >=2.*
    - dash-table # this seems to be needed by pip check, but probably not by the package if dash >=2.*
    - dash_cytoscape >=0.1.1
    - gevent >=1.3.6
    - requests >=2.19.0
    # pure test requirements
    - pytest >=4.3.0
    - pytest-runner >=4.4
    - pytest-xdist >=1.29
    - nbconvert >=5.4.1
    - selenium >=3.141.0
    - pytest-cov >=2.6.1
    # ----remove linter temporarily   - flake8 >=3.7.7
    - jupyter >=1.0.0
    - ipywidgets >=7.4.2
  imports:
    - interpret
  source_files:
    - python/interpret-core/interpret/glassbox/ebm/test/test_*.py
  commands:
    - pip check
    - ls
    #- pytest
    - pytest --pyargs interpret

about:
  home: https://github.com/interpretml/interpret
  summary: Fit interpretable machine learning models. Explain blackbox machine learning.
  description: |
    Core system for **the** interpret package.

    https://github.com/interpretml/interpret
  license: MIT
  license_file: LICENSE
  doc_url: https://interpret.ml/docs/getting-started
  dev_url: https://interpret.ml/docs/installation-guide.html

extra:
  recipe-maintainers:
    - paulbkoch
    - interpret-ml
