{% set name = "interpret-core" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/interpretml/interpret/archive/b1fbf0f59c60aae0f92c305101855ec150dd3b1b.tar.gz
  # curl -sL https://github.com/interpretml/interpret/archive/b1fbf0f59c60aae0f92c305101855ec150dd3b1b.tar.gz | openssl sha256
  sha256: 29fc2de686a696402360c6df53439646d39f8d74e221fecca0199d874d656c06
  # url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  # url: https://github.com/interpretml/interpret/releases/download/{{ version }}/interpret-core-{{ version }}.tar.gz
  # url: https://github.com/interpretml/interpret/archive/v{{ version }}.tar.gz
  # git_url: https://github.com/interpretml/interpret.git
  # git_rev: "v{{ version }}"
  # git_depth: 1

build:
  number: 0
  skip: True  # [py<=36 or py>=310]
  script: cd ./python/interpret-core/ && {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - setuptools
    - wheel
    # specifying nodejs ==* prevents us from building it 3 times for different versions of nodejs (after running @conda-forge-admin please rerender)
    - nodejs ==16.*
  run:
    - python
  run_constrained:
    # in setup.py
    - setuptools
    - wheel
    # Equiv. to required.
    - numpy >=1.11.1
    - scipy >=0.18.1
    - pandas >=0.19.2
    - scikit-learn >=0.18.1
    - joblib >=0.11
    # Equiv. to extras.
    - psutil >=5.6.2
    - ipykernel >=5.1.0
    - ipython >=7.4.0
    - plotly >=3.8.1
    - lime >=0.1.1.33
    - SALib >=1.3.3
    - shap >=0.28.5
    - dill >=0.2.5
    - skope-rules >=1.0.1
    - treeinterpreter >=0.2.2
    - dash >=1.0.0
    - dash_cytoscape >=0.1.1
    - gevent >=1.3.6
    - requests >=2.19.0

test:
  requires:
    # in setup.py
    - setuptools
    - wheel
    # Equiv. to required.
    - numpy >=1.11.1
    - scipy >=0.18.1
    - pandas >=0.19.2
    - scikit-learn >=0.18.1
    - joblib >=0.11
    # Equiv. to extras.
    - psutil >=5.6.2
    - ipykernel >=5.1.0
    - ipython >=7.4.0
    - plotly >=3.8.1
    - lime >=0.1.1.33
    - SALib >=1.3.3
    - shap >=0.28.5
    - dill >=0.2.5
    - skope-rules >=1.0.1
    - treeinterpreter >=0.2.2
    - dash >=1.0.0
    - dash_cytoscape >=0.1.1
    - gevent >=1.3.6
    - requests >=2.19.0
    # pure test requirements
    - pytest >=4.3.0
    - pytest-runner >=4.4
    - pytest-xdist >=1.29
    - nbconvert >=5.4.1
    - selenium >=3.141.0
    - pytest-cov >=2.6.1
    - flake8 >=3.7.7
    - jupyter >=1.0.0
    - ipywidgets >=7.4.2
  imports:
    - interpret

about:
  home: https://github.com/interpretml/interpret
  summary: Fit interpretable machine learning models. Explain blackbox machine learning.
  description: |
    Core system for **the** interpret package.

    https://github.com/interpretml/interpret
  license: MIT
  license_file: LICENSE
  doc_url: https://interpret.ml/docs/getting-started
  dev_url: https://interpret.ml/docs/installation-guide.html

extra:
  recipe-maintainers:
    - paulbkoch
    - interpret-ml
